# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Black Duck Security Action allows you to integrate Static Analysis Security Testing (SAST) and Software Composition Analysis (SCA) into your CI/CD pipelines.
# For more information about configuring your workflow,
# read our documentation at https://github.com/blackduck-inc/black-duck-security-scan

name: CI Black Duck security scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '21 2 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
      actions: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
# --- NPM 빌드를 위해 추가한 부분 ----
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
         node-version: '20.x'
         
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
# ----------------------------------
        
      - name: Black Duck SCA scan
        uses: blackduck-inc/black-duck-security-scan@805cbd09e806b01907bbea0f990723c2bb85abe9
        with:
          ### ---------- BLACKDUCK SCA SCANNING: REQUIRED FIELDS ----------
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
          network_ssl_trustAll: true
          blackduck_waitForScan: true
          github_token: ${{ secrets.GIT_TOKEN }}
          blackducksca_fixpr_enabled: true
          blackducksca_reports_sarif_create: true
          blackducksca_upload_sarif_report: true
          blackducksca_fixpr_useUpgradeGuidance: SHORT_TERM, LONG_TERM
